version: "3"

services:

  phantom:
    image: albertomartins/phantomjs-nanohttpd-executor
    ports:
      - 80:8080
    # service deployment
    deploy:
      mode: replicated
      replicas: 4
      labels: [APP=PHANTOM]
      # service resource management
      resources:
        # Hard limit - Docker does not allow to allocate more
        limits:
          cpus: '0.25'
          memory: 512M
        # Soft limit - Docker makes best effort to return to it
        reservations:
          cpus: '0.25'
          memory: 256M
      # service restart policy
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
      # service update configuration
      update_config:
        parallelism: 1
        delay: 10s
        failure_action: continue
        monitor: 60s
        max_failure_ratio: 0.3

networks:
    phantom: